version: '3.8'
services:
  sms_backend:
    build: .
    container_name: sms_backend
    restart: always
    ports:
      - "8080:8080"
    networks:
      - spring-net
    depends_on:
      - sms_database

  sms_database:
    container_name: sms_database
    image: mysql:8.0
    restart: always
    networks:
      - spring-net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smsdatabase
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    ports:
      - '3306:3306'
    volumes:
      - dbstore:/var/lib/mysql

volumes:
  dbstore:

networks:
  spring-net: